### ISSUE TITLE
Ticker allowed characters

### ISSUE THREAD

**Issue by asoltys** [Blockstream/asset_registry_db#2]
According to this spec, tickers can contain numbers: https://docs.blockstream.com/liquid/developer-guide/developer-guide-index.html#contract-json-fields

But I'm getting an error when trying to register assets with numbers in the ticker: Asset registration failed invalid `ticker`

**Comment by shesek** [comment]
Yes, ticker names can contain numbers. Which ticker string were you trying to use?

It has to be 3-5 characters, consisting of `0-9`, `a-z`, `A-Z`, `.` or `-`.

**Comment by asoltys** [comment]
Ah my bad, it was the length requirement not the number that got me, I was trying to register a 2-character ticker. Thanks shesek
